import type { ReviewResult, ReviewSection } from '@spex/schemas';
import { describe, expect, it } from 'vitest';
import { formatReviewAsMarkdown } from './formatter.js';

const emptySection: ReviewSection = { findings: [], summary: 'No findings.' };

function makeResult(overrides: Partial<ReviewResult> = {}): ReviewResult {
  return {
    spec_compliance: emptySection,
    conventions: emptySection,
    performance_security: emptySection,
    test_coverage: emptySection,
    overall_summary: 'Overall good.',
    recommendation: 'approve',
    ...overrides,
  };
}

describe('formatReviewAsMarkdown', () => {
  it('includes the recommendation badge and overall summary', () => {
    const md = formatReviewAsMarkdown(makeResult());
    expect(md).toContain('# SPEX Review');
    expect(md).toContain('**Recommendation:** ✅ Approve');
    expect(md).toContain('Overall good.');
  });

  it('renders all four section headings even when empty', () => {
    const md = formatReviewAsMarkdown(makeResult());
    expect(md).toContain('## Spec compliance');
    expect(md).toContain('## Conventions');
    expect(md).toContain('## Performance & security');
    expect(md).toContain('## Test coverage');
  });

  it('renders findings with severity badges and locators', () => {
    const md = formatReviewAsMarkdown(
      makeResult({
        spec_compliance: {
          findings: [
            {
              severity: 'major',
              message: 'Scope.out lists "Pagination UI" but diff adds a Pager component.',
              file: 'src/components/pager.tsx',
              lines: '1-12',
            },
            { severity: 'minor', message: 'Inconsistent indentation.' },
          ],
          summary: 'One major scope violation.',
        },
        recommendation: 'request_changes',
      }),
    );
    expect(md).toContain('🟠 major');
    expect(md).toContain('🟡 minor');
    expect(md).toContain('`src/components/pager.tsx:1-12`');
    expect(md).toContain('**Recommendation:** ⛔ Request changes');
  });

  it('includes the SPEX footer', () => {
    expect(formatReviewAsMarkdown(makeResult())).toContain('Generated by [SPEX]');
  });
});
