import type { ReviewFinding, ReviewResult, ReviewSection, ReviewSeverity } from '@spex/schemas';

const SEVERITY_BADGES: Record<ReviewSeverity, string> = {
  info: 'ℹ️ info',
  minor: '🟡 minor',
  major: '🟠 major',
  blocker: '🔴 blocker',
};

const RECOMMENDATION_LABELS: Record<ReviewResult['recommendation'], string> = {
  approve: '✅ Approve',
  comment: '💬 Comment',
  request_changes: '⛔ Request changes',
};

const SECTION_HEADINGS: Record<
  keyof Omit<ReviewResult, 'overall_summary' | 'recommendation'>,
  string
> = {
  spec_compliance: 'Spec compliance',
  conventions: 'Conventions',
  performance_security: 'Performance & security',
  test_coverage: 'Test coverage',
};

export function formatReviewAsMarkdown(review: ReviewResult): string {
  const parts: string[] = [];
  parts.push('# SPEX Review');
  parts.push(`**Recommendation:** ${RECOMMENDATION_LABELS[review.recommendation]}`);
  parts.push(`\n${review.overall_summary.trim()}`);

  for (const key of Object.keys(SECTION_HEADINGS) as (keyof typeof SECTION_HEADINGS)[]) {
    parts.push(`\n## ${SECTION_HEADINGS[key]}`);
    parts.push(formatSection(review[key]));
  }

  parts.push(
    '\n---\n_Generated by [SPEX](https://github.com/rogcg/spex) — spec-driven AI orchestration._',
  );
  return parts.join('\n');
}

function formatSection(section: ReviewSection): string {
  if (section.findings.length === 0) {
    return `_${section.summary.trim()}_`;
  }
  const lines: string[] = [];
  lines.push(`_${section.summary.trim()}_`);
  lines.push('');
  for (const finding of section.findings) {
    lines.push(formatFinding(finding));
  }
  return lines.join('\n');
}

function formatFinding(finding: ReviewFinding): string {
  const badge = SEVERITY_BADGES[finding.severity];
  const locator = formatLocator(finding);
  return `- **${badge}**${locator ? ` ${locator}` : ''} — ${finding.message.trim()}`;
}

function formatLocator(finding: ReviewFinding): string {
  if (!finding.file && !finding.lines) return '';
  if (finding.file && finding.lines) return `\`${finding.file}:${finding.lines}\``;
  if (finding.file) return `\`${finding.file}\``;
  return `lines \`${finding.lines}\``;
}
