import type { LLMProvider } from '@spex/core';
import { z } from 'zod';
import type { PrDescription } from './template.js';

const PolishedPrSchema = z
  .object({
    title: z.string().min(1).max(200, 'PR title must be at most 200 characters'),
    body: z.string().min(1),
  })
  .strict();

export interface PolishPrDescriptionOptions {
  llm: LLMProvider;
  template: PrDescription;
  /**
   * Optional extra context passed verbatim to the model. Useful for surfacing
   * project-specific conventions (e.g. "use Conventional Commits prefixes").
   */
  extraInstructions?: string;
}

const SYSTEM_PROMPT = [
  'You polish pull request descriptions generated by an automated tool (SPEX).',
  'Your goal is to make the description clearer and more readable WITHOUT inventing facts.',
  '',
  'Rules:',
  '- Preserve all factual content from the input (file paths, SHAs, branch names, test paths).',
  '- Preserve the section headings provided in the input. You may merge or reorder when it improves readability.',
  '- Do NOT invent file paths, commit SHAs, dependency names, or test paths.',
  '- Do NOT remove the SPEX footer ("Generated by SPEX...").',
  '- Keep the title concise and aligned with Conventional Commits when appropriate.',
  '- The body MUST be valid GitHub-flavoured Markdown.',
].join('\n');

/**
 * Ask the LLM to polish a template PR description while preserving all
 * factual content. On any error (network, schema mismatch, etc.) returns the
 * original template unchanged — never throws.
 */
export async function polishPrDescription(
  options: PolishPrDescriptionOptions,
): Promise<PrDescription> {
  const userPrompt = buildUserPrompt(options.template, options.extraInstructions);
  try {
    const polished = await options.llm.generateStructured({
      systemPrompt: SYSTEM_PROMPT,
      userPrompt,
      schema: PolishedPrSchema,
    });
    return { title: polished.title, body: polished.body };
  } catch {
    return options.template;
  }
}

function buildUserPrompt(template: PrDescription, extra?: string): string {
  const sections = [
    'Polish the following PR description. Keep all facts intact.',
    '',
    `--- INPUT TITLE ---\n${template.title}`,
    `--- INPUT BODY ---\n${template.body}`,
  ];
  if (extra && extra.trim().length > 0) {
    sections.push(`--- EXTRA INSTRUCTIONS ---\n${extra.trim()}`);
  }
  sections.push(
    '--- OUTPUT ---',
    'Return a JSON object with two string fields: "title" and "body".',
  );
  return sections.join('\n');
}
