import { describe, expect, it } from 'vitest';
import { buildFeaturePrTemplate, buildFixPrTemplate, buildPrTemplate } from './template.js';

describe('buildFeaturePrTemplate', () => {
  const baseInput = {
    kind: 'feature' as const,
    featureSlug: 'add-pagination',
    featureTitle: 'Add pagination to issues list',
    featureDescription: 'Users should see pagination controls when there are more than 30 issues.',
    technicalApproach:
      'Wrap the existing list query with offset/limit and render a Pager component.',
    testCases: ['Renders next button when total > pageSize', 'Hides pager when total <= pageSize'],
    filesAffected: [
      { path: 'src/components/issues-list.tsx', operation: 'modify' },
      { path: 'src/components/pager.tsx', operation: 'create' },
    ],
    featureSpecRelativePath: '.ai/specs/features/add-pagination/feature-spec.yaml',
    techSpecRelativePath: '.ai/tech-spec.yaml',
    branch: 'feature/add-pagination',
    baseBranch: 'main',
    commits: [
      { sha: 'a1b2c3d4e5f6abcd', subject: 'feat(add-pagination): add pager component' },
      { sha: 'f6e5d4c3b2a19876', subject: 'test(add-pagination): cover pager edge cases' },
    ],
  };

  it('formats a conventional title from slug + feature title', () => {
    const result = buildFeaturePrTemplate(baseInput);
    expect(result.title).toBe('feat(add-pagination): Add pagination to issues list');
  });

  it('includes summary, technical approach, files affected, test plan, and references', () => {
    const result = buildFeaturePrTemplate(baseInput);
    expect(result.body).toContain('## Summary');
    expect(result.body).toContain('## Technical approach');
    expect(result.body).toContain('## Files affected');
    expect(result.body).toContain('## Test plan');
    expect(result.body).toContain('## References');
    expect(result.body).toContain('`.ai/specs/features/add-pagination/feature-spec.yaml`');
    expect(result.body).toContain('`.ai/tech-spec.yaml`');
  });

  it('lists files with their operations', () => {
    const result = buildFeaturePrTemplate(baseInput);
    expect(result.body).toContain('- `src/components/issues-list.tsx` — modify');
    expect(result.body).toContain('- `src/components/pager.tsx` — create');
  });

  it('renders commits with truncated SHAs', () => {
    const result = buildFeaturePrTemplate(baseInput);
    expect(result.body).toContain('`a1b2c3d4e5` feat(add-pagination): add pager component');
    expect(result.body).toContain('`f6e5d4c3b2` test(add-pagination): cover pager edge cases');
  });

  it('omits the References section entirely when both paths are null', () => {
    const result = buildFeaturePrTemplate({
      ...baseInput,
      featureSpecRelativePath: null,
      techSpecRelativePath: null,
    });
    expect(result.body).not.toContain('## References');
  });

  it('includes the SPEX footer', () => {
    const result = buildFeaturePrTemplate(baseInput);
    expect(result.body).toContain('Generated by [SPEX]');
  });

  it('omits the Linear section by default', () => {
    const result = buildFeaturePrTemplate(baseInput);
    expect(result.body).not.toContain('## Linear');
    expect(result.body).not.toContain('Closes [');
  });

  it('adds a `Closes <id>` line when linearIssue is provided', () => {
    const result = buildFeaturePrTemplate({
      ...baseInput,
      linearIssue: {
        identifier: 'SPX-47',
        url: 'https://linear.app/spex/issue/SPX-47',
      },
    });
    expect(result.body).toContain('## Linear');
    expect(result.body).toContain('Closes [SPX-47](https://linear.app/spex/issue/SPX-47)');
  });
});

describe('buildFixPrTemplate', () => {
  const baseFix = {
    kind: 'fix' as const,
    hypothesisDescription: 'Cache invalidation runs before write commits.',
    rootCauseSummary:
      'The invalidation hook fires on optimistic update, not after mutation success.',
    selectedFixLabel: 'Move invalidation to onSuccess callback',
    selectedFixScope: 'narrow',
    selectedFixRisk: 'low',
    regressionTestPath: 'tests/cache-invalidation.test.ts',
    techSpecRelativePath: '.ai/tech-spec.yaml',
    branch: 'fix/cache-invalidation',
    baseBranch: 'main',
    commits: [{ sha: 'deadbeefcafe0000', subject: 'fix(cache): move invalidation to onSuccess' }],
  };

  it('formats a fix-prefixed title from the hypothesis description', () => {
    const result = buildFixPrTemplate(baseFix);
    expect(result.title).toBe('fix: Cache invalidation runs before write commits.');
  });

  it('includes hypothesis, root cause, selected fix, regression test, and references sections', () => {
    const result = buildFixPrTemplate(baseFix);
    expect(result.body).toContain('## Hypothesis');
    expect(result.body).toContain('## Root cause');
    expect(result.body).toContain('## Selected fix');
    expect(result.body).toContain('## Regression test');
    expect(result.body).toContain('## References');
    expect(result.body).toContain('`tests/cache-invalidation.test.ts`');
  });

  it('renders scope + risk in the Selected fix section', () => {
    const result = buildFixPrTemplate(baseFix);
    expect(result.body).toContain('**Scope:** narrow');
    expect(result.body).toContain('**Risk:** low');
  });

  it('omits Regression test section when regressionTestPath is null', () => {
    const result = buildFixPrTemplate({ ...baseFix, regressionTestPath: null });
    expect(result.body).not.toContain('## Regression test');
  });
});

describe('buildPrTemplate', () => {
  it('dispatches by kind', () => {
    const feature = buildPrTemplate({
      kind: 'feature',
      featureSlug: 'x',
      featureTitle: 'X',
      featureDescription: 'desc',
      technicalApproach: 'approach',
      testCases: ['t1'],
      filesAffected: [{ path: 'a', operation: 'create' }],
      featureSpecRelativePath: null,
      techSpecRelativePath: null,
      branch: 'feature/x',
      baseBranch: 'main',
      commits: [],
    });
    expect(feature.title).toMatch(/^feat\(/);

    const fix = buildPrTemplate({
      kind: 'fix',
      hypothesisDescription: 'bug',
      rootCauseSummary: 'cause',
      selectedFixLabel: 'patch',
      selectedFixScope: 'narrow',
      selectedFixRisk: 'low',
      regressionTestPath: null,
      techSpecRelativePath: null,
      branch: 'fix/y',
      baseBranch: 'main',
      commits: [],
    });
    expect(fix.title).toMatch(/^fix:/);
  });
});
