export interface PrCommitInfo {
  sha: string;
  subject: string;
}

export interface FeaturePrInput {
  kind: 'feature';
  featureSlug: string;
  featureTitle: string;
  featureDescription: string;
  technicalApproach: string;
  testCases: readonly string[];
  filesAffected: readonly { path: string; operation: string }[];
  featureSpecRelativePath: string | null;
  techSpecRelativePath: string | null;
  branch: string;
  baseBranch: string;
  commits: readonly PrCommitInfo[];
  /** Optional Linear issue this PR resolves. Renders as a `Closes` reference. */
  linearIssue?: { identifier: string; url: string };
}

export interface FixPrInput {
  kind: 'fix';
  hypothesisDescription: string;
  rootCauseSummary: string;
  selectedFixLabel: string;
  selectedFixScope: string;
  selectedFixRisk: string;
  regressionTestPath: string | null;
  techSpecRelativePath: string | null;
  branch: string;
  baseBranch: string;
  commits: readonly PrCommitInfo[];
}

export type PrDescriptionInput = FeaturePrInput | FixPrInput;

export interface PrDescription {
  title: string;
  body: string;
}

const SHA_DISPLAY_LENGTH = 10;

export function buildPrTemplate(input: PrDescriptionInput): PrDescription {
  if (input.kind === 'feature') {
    return buildFeaturePrTemplate(input);
  }
  return buildFixPrTemplate(input);
}

export function buildFeaturePrTemplate(input: FeaturePrInput): PrDescription {
  const title = `feat(${input.featureSlug}): ${input.featureTitle}`;
  const sections: string[] = [];

  sections.push(`## Summary\n\n${input.featureDescription.trim()}`);

  if (input.linearIssue) {
    sections.push(
      `## Linear\n\nCloses [${input.linearIssue.identifier}](${input.linearIssue.url})`,
    );
  }

  sections.push(`## Technical approach\n\n${input.technicalApproach.trim()}`);

  if (input.filesAffected.length > 0) {
    const lines = input.filesAffected.map((f) => `- \`${f.path}\` — ${f.operation}`);
    sections.push(`## Files affected\n\n${lines.join('\n')}`);
  }

  if (input.testCases.length > 0) {
    const lines = input.testCases.map((c) => `- ${c}`);
    sections.push(`## Test plan\n\n${lines.join('\n')}`);
  }

  const refs = buildReferences({
    featureSpecRelativePath: input.featureSpecRelativePath,
    techSpecRelativePath: input.techSpecRelativePath,
  });
  if (refs) sections.push(refs);

  sections.push(buildCommitsSection(input.commits, input.branch, input.baseBranch));
  sections.push(SPEX_FOOTER);

  return { title, body: sections.join('\n\n') };
}

export function buildFixPrTemplate(input: FixPrInput): PrDescription {
  const title = `fix: ${input.hypothesisDescription}`;
  const sections: string[] = [];

  sections.push(`## Hypothesis\n\n${input.hypothesisDescription.trim()}`);

  sections.push(`## Root cause\n\n${input.rootCauseSummary.trim()}`);

  const fixLines = [
    `- **Approach:** ${input.selectedFixLabel}`,
    `- **Scope:** ${input.selectedFixScope}`,
    `- **Risk:** ${input.selectedFixRisk}`,
  ];
  sections.push(`## Selected fix\n\n${fixLines.join('\n')}`);

  if (input.regressionTestPath) {
    sections.push(`## Regression test\n\n\`${input.regressionTestPath}\``);
  }

  const refs = buildReferences({
    featureSpecRelativePath: null,
    techSpecRelativePath: input.techSpecRelativePath,
  });
  if (refs) sections.push(refs);

  sections.push(buildCommitsSection(input.commits, input.branch, input.baseBranch));
  sections.push(SPEX_FOOTER);

  return { title, body: sections.join('\n\n') };
}

function buildReferences(opts: {
  featureSpecRelativePath: string | null;
  techSpecRelativePath: string | null;
}): string | null {
  const refs: string[] = [];
  if (opts.featureSpecRelativePath) {
    refs.push(`- Feature spec: \`${opts.featureSpecRelativePath}\``);
  }
  if (opts.techSpecRelativePath) {
    refs.push(`- Tech spec: \`${opts.techSpecRelativePath}\``);
  }
  if (refs.length === 0) return null;
  return `## References\n\n${refs.join('\n')}`;
}

function buildCommitsSection(
  commits: readonly PrCommitInfo[],
  branch: string,
  baseBranch: string,
): string {
  const header = `## Commits\n\nBranch \`${branch}\` → \`${baseBranch}\``;
  if (commits.length === 0) {
    return header;
  }
  const lines = commits.map((c) => `- \`${c.sha.slice(0, SHA_DISPLAY_LENGTH)}\` ${c.subject}`);
  return `${header}\n\n${lines.join('\n')}`;
}

const SPEX_FOOTER =
  '---\n_Generated by [SPEX](https://github.com/rogcg/spex) — spec-driven AI orchestration._';
